### PR TITLE
[BB2-1475] Readme updates

### PR DESCRIPTION
**Pull request by mrengy**
**Jira ticket**
https://jira.cms.gov/browse/BB2-1475

**User story or bug summary**
Currently the readme at https://github.com/CMSgov/bluebutton-site-static is misleading and makes it easy to go down the path of installing Jekyll and versioned Ruby manually. This is error-prone. Refactor the readme to direct people to using Docker instead.

### What Does This PR Do?
Updates readme to resolve installation issues. Also adding a .ruby-version file to specify the ruby version for using chruby. There really should not be any dependencies.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check these things, in particular:

* TODO

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence: N/A.
    * Does this PR add any new software dependencies?  **No**.
    * Does this PR modify or invalidate any of our security controls? **No**.
    * Does this PR store or transmit data that was not stored or transmitted before? **No**.
* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR should not be merged unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons? **No**.

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following pre-requisite changes have been fully deployed:

* CMSgov/some_repo#42

### Submitter Checklist

I have gone through and verified that...:

* [x] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [ ] I have named this PR and its branch such that they'll be automatically be linked to the (most) relevant Jira issue, per: <https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html>.
* [x] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [x] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [x] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [x] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. BFD, SLS, etc.).
* [x] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Review by dtisza1 — CHANGES_REQUESTED** [review]
@mrengy Just a few change requests for the title, description and related to Docker.

- The title should follow our convention for:    "[ BB2-xxxx ] Readme updates"
  - With the Jira ticket number.
- The Jira ticket should be referenced in the PR template (PR description text). See one of the BB2 webserver API PR's as an example and to copy the needed text from:  https://github.com/CMSgov/bluebutton-web-server/pull/966

For developing locally, we should use Docker / docker-compose per this HOW-TO in confluence:  https://confluence.cms.gov/pages/viewpage.action?spaceKey=BB2&title=HOW-TO+Static+Site+Updates

Since we all have different desktop environments, using docker will help to keep it compatible for everyone.

There is  a section in the README related to this:

    - NOTE: Internal software engineers or other interested parties should follow the documentation for running a Dockerized local development enviornment. For more information see the [Dockerized Setup](https://github.com/CMSgov/bluebutton-site-static#dockerized-setup) section.


I was able to test the changes you made outside of docker.  When installing with the master branch I was getting errors. Using your branch worked for me. 

The following line in the `Dockerfile` needs updated for this to work with docker-compose:
```
FROM ruby:3.1.2
```

This worked for me when testing.

**Comment by mrengy** [comment]
Thanks. I totally missed that note about using Docker. I'll rework this
accordingly with the title and Jira ticket and also see about making the
readme more clear to use Docker as the primary way to install.

**Comment by mrengy** [comment]
@dtisza1 (I think) I made the requested edits to the original PR comment and the PR name. Do I need to change the branch name too? I'm not sure off-hand how to do that.

Also I made more changes to the readme as additional commits in order to make it more clear to use Docker.

**Review by ajshred — APPROVED** [review]
I think this looks good.  There are minor differences in the naming of the branch/PR, but I don't think any more changes are necessary for this to be merged.  Thanks Mike for doing this!  Good job!!

**Review by dtisza1 — APPROVED** [review]
@mrengy This looks good to me!

TY for the updates per the change requests!

The branch name is OK.  For future branch naming, the following would be a good example:

`mrengy/BB2-1475-readme-updates`

The README.md is much better now! Before if quickly reading it, the use of docker wasn't clear. This is much better.  Good work on this!

**Pull request merged**
