### PR TITLE
Cbbm 107

### PR DESCRIPTION
**Pull request by jcgeer**
Adding the Implementation Guide to the Blue Button static site.

### CODE REVIEW

**Comment by kellytaylorgov** [comment]
Adding @whytheplatypus for another quick review.  Notice how many files we are adding to assets/ig,  just wanted to make sure you have visibility on this.

@jcgeer let's add Google Analytics and link to the IG from our FHIR Data Model page, see Jira for specifics.

**Comment by jcgeer** [comment]
I will work on adding Google Analytics and I can also do a write-up on how everything was generated/how modifications can be made.

As far as the number of files... We used a tool called IG Publisher that took our original files and ran them through a specific Jekyll build to create the HTML docs/assets for the site, namely the differential/snapshot views based on our profiles. We then copied all those output files over into this site.

**Comment by ekivemark** [comment]
@jcgeer:
When running the ig code I get a series of errors for images that are not found:

[2018-05-29 10:08:19] ERROR `/assets/ig/assets/css/images/ui-bg_glass_100_f6f6f6_1x400.png' not found.
[2018-05-29 10:08:19] ERROR `/assets/ig/assets/css/images/ui-bg_glass_65_ffffff_1x400.png' not found.
[2018-05-29 10:09:10] ERROR `/assets/ig/tbl_bck11001.png' not found.
[2018-05-29 10:09:10] ERROR `/assets/ig/tbl_bck110000.png' not found.
[2018-05-29 10:09:10] ERROR `/assets/ig/tbl_bck110010.png' not found.
[2018-05-29 10:09:10] ERROR `/assets/ig/tbl_bck11111.png' not found.
[2018-05-29 10:09:10] ERROR `/assets/ig/tbl_bck111110.png' not found.
[2018-05-29 10:09:10] ERROR `/assets/ig/tbl_bck111100.png' not found.
[2018-05-29 10:09:10] ERROR `/assets/ig/tbl_bck10101.png' not found.
[2018-05-29 10:09:10] ERROR `/assets/ig/tbl_bck101010.png' not found.
[2018-05-29 10:09:10] ERROR `/assets/ig/tbl_bck101000.png' not found.
[2018-05-29 10:09:10] ERROR `/assets/ig/assets/css/images/ui-bg_glass_100_f6f6f6_1x400.png' not found.
[2018-05-29 10:09:10] ERROR `/assets/ig/assets/css/images/ui-bg_glass_65_ffffff_1x400.png' not found.
[2018-05-29 10:09:35] ERROR `/assets/ig/assets/css/images/ui-bg_glass_100_fdf5ce_1x400.png' not found.

**Comment by jcgeer** [comment]
I'll look into those errors.

**Comment by ekivemark** [comment]
@kellytaylorgov  I have added a section to the Developer documentation for the FHIR Implementation Guide. I have also drafted a blog on the subject of the IG.
I also added a link on the index.html file back to the Developer Documentation.

**Comment by jcgeer** [comment]
I've added Google Analytics to the pages, as well as fixed the image errors Mark mentioned. Is there a test I can perform to ensure the analytics are working correctly?

**Pull request merged**
